<center>
    <img src="https://drive.google.com/uc?export=view&id=1hDKusF04c0lNZA_qOShvWQrpImayVKz8"  width="1000" />
</center>

# Tugas Mandiri
---
Tugas mandiri ini digunakan pada kegiatan Kursus Data Science yang merupakan pembekalan bagi mahasiswa Universitas Gunadarma untuk Skema Associate Data Scientist

##### Pertemuan 5 - Semester 7
#### Benedictus Adolf Josevan Sarumpaet / 4IA07 / 50421272

## **No 1. Cari Dataset**

Dataset **SAheart.csv** didapatkan dari website Kaggle

Dataset dapat diakses melalui link berikut : https://www.kaggle.com/datasets/waalbannyantudre/south-african-heart-disease-dataset

## **No 2. Tujuan Pembuatan Proyek dan Deskripsi Dataset**

### Tujuan pembuatan proyek :
Memprediksi chd berdasarkan obesitas dan alcohol

### Deskripsi dataset :
- **sbp** : Systolic blood pressure
- **tobacco** : Cumulative tobacco (kg)
- **ldl** :	Low density lipoprotein cholesterol level
- **adiposity**	: Severe overweight (a numeric vector)
- **famhist** :	Family history of heart disease
- **typea** :Type-A behavior
- **obesity** :	Excessive fat accumulation (a numeric vector)
- **alcohol** :	Current alcohol consumption
- **age** :	Age at onset
- **chd** :	Response, coronary heart

## **No 3. Tahapan CRISP DM**

### 1. Business Understanding

#### Tujuan: Memprediksi chd (pernah kena sakit jantung) berdasarkan obesitas dan alcohol

### 2. Data Understanding

Import Dataset

In [1]:
# Import Library
import pandas as pd
import numpy as np

In [2]:
# Membaca data
df = pd.read_csv('SAHeart.csv')

In [3]:
# Melihat dimensi (jumlah baris dan kolom) data
df.shape

(462, 11)

In [4]:
df.head(5)

,row.names,sbp,tobacco,ldl,adiposity,famhist,typea,obesity,alcohol,age,chd
0,1,160,12.00,5.73,23.11,Present,49,25.30,97.20,52,1
1,2,144,0.01,4.41,28.61,Absent,55,28.87,2.06,63,1
2,3,118,0.08,3.48,32.28,Present,52,29.14,3.81,46,0
3,4,170,7.50,6.41,38.03,Present,51,31.99,24.26,58,1
4,5,134,13.60,3.50,27.78,Present,60,25.99,57.34,49,1

In [5]:
df.tail(5)

,row.names,sbp,tobacco,ldl,adiposity,famhist,typea,obesity,alcohol,age,chd
457,459,214,0.4,5.98,31.72,Absent,64,28.45,0.00,58,0
458,460,182,4.2,4.41,32.10,Absent,52,28.61,18.72,52,1
459,461,108,3.0,1.59,15.23,Absent,40,20.09,26.64,55,0
460,462,118,5.4,11.61,30.79,Absent,64,27.35,23.97,40,0
461,463,132,0.0,4.82,33.41,Present,62,14.70,0.00,46,1

In [6]:
# Mengetahui tipe data
df.dtypes

row.names      int64
sbp            int64
tobacco      float64
ldl          float64
adiposity    float64
famhist       object
typea          int64
obesity      float64
alcohol      float64
age            int64
chd            int64
dtype: object

In [7]:
df.select_dtypes(exclude="object").head()

   row.names  sbp  tobacco   ldl  adiposity  typea  obesity  alcohol  age  chd
0          1  160    12.00  5.73      23.11     49    25.30    97.20   52    1
1          2  144     0.01  4.41      28.61     55    28.87     2.06   63    1
2          3  118     0.08  3.48      32.28     52    29.14     3.81   46    0
3          4  170     7.50  6.41      38.03     51    31.99    24.26   58    1
4          5  134    13.60  3.50      27.78     60    25.99    57.34   49    1

In [8]:
# Menampilkan statisti
df.describe()

,row.names,sbp,tobacco,ldl,adiposity,typea,obesity,alcohol,age,chd
count,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000
mean,231.935065,138.326840,3.635649,4.740325,25.406732,53.103896,26.044113,17.044394,42.816017,0.346320
std,133.938585,20.496317,4.593024,2.070909,7.780699,9.817534,4.213680,24.481059,14.608956,0.476313
min,1.000000,101.000000,0.000000,0.980000,6.740000,13.000000,14.700000,0.000000,15.000000,0.000000
25%,116.250000,124.000000,0.052500,3.282500,19.775000,47.000000,22.985000,0.510000,31.000000,0.000000
50%,231.500000,134.000000,2.000000,4.340000,26.115000,53.000000,25.805000,7.510000,45.000000,0.000000
75%,347.750000,148.000000,5.500000,5.790000,31.227500,60.000000,28.497500,23.892500,55.000000,1.000000
max,463.000000,218.000000,31.200000,15.330000,42.490000,78.000000,46.580000,147.190000,64.000000,1.000000

In [9]:
# Menampilkan statistik kolom numerik dan non numerik
df.describe(include='all')

,row.names,sbp,tobacco,ldl,adiposity,famhist,typea,obesity,alcohol,age,chd
count,462.000000,462.000000,462.000000,462.000000,462.000000,462,462.000000,462.000000,462.000000,462.000000,462.000000
unique,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,Absent,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,270,NaN,NaN,NaN,NaN,NaN
mean,231.935065,138.326840,3.635649,4.740325,25.406732,NaN,53.103896,26.044113,17.044394,42.816017,0.346320
std,133.938585,20.496317,4.593024,2.070909,7.780699,NaN,9.817534,4.213680,24.481059,14.608956,0.476313
min,1.000000,101.000000,0.000000,0.980000,6.740000,NaN,13.000000,14.700000,0.000000,15.000000,0.000000
25%,116.250000,124.000000,0.052500,3.282500,19.775000,NaN,47.000000,22.985000,0.510000,31.000000,0.000000
50%,231.500000,134.000000,2.000000,4.340000,26.115000,NaN,53.000000,25.805000,7.510000,45.000000,0.000000
75%,347.750000,148.000000,5.500000,5.790000,31.227500,NaN,60.000000,28.497500,23.892500,55.000000,1.000000
max,463.000000,218.000000,31.200000,15.330000,42.490000,NaN,78.000000,46.580000,147.190000,64.000000,1.000000

### 3. Data Preparation

In [10]:
# Membuang Kolom "row-names"
df = df.iloc[:,1:]

In [11]:
df.head()

   sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
0  160    12.00  5.73      23.11  Present     49    25.30    97.20   52    1
1  144     0.01  4.41      28.61   Absent     55    28.87     2.06   63    1
2  118     0.08  3.48      32.28  Present     52    29.14     3.81   46    0
3  170     7.50  6.41      38.03  Present     51    31.99    24.26   58    1
4  134    13.60  3.50      27.78  Present     60    25.99    57.34   49    1

In [12]:
df.isna().sum()

sbp          0
tobacco      0
ldl          0
adiposity    0
famhist      0
typea        0
obesity      0
alcohol      0
age          0
chd          0
dtype: int64

In [13]:
df.isnull().any()

sbp          False
tobacco      False
ldl          False
adiposity    False
famhist      False
typea        False
obesity      False
alcohol      False
age          False
chd          False
dtype: bool

In [14]:
df.isna().sum()

sbp          0
tobacco      0
ldl          0
adiposity    0
famhist      0
typea        0
obesity      0
alcohol      0
age          0
chd          0
dtype: int64

In [15]:
# Memilih kolom dengan tipe data selain object
df.select_dtypes(exclude="object").head()

   sbp  tobacco   ldl  adiposity  typea  obesity  alcohol  age  chd
0  160    12.00  5.73      23.11     49    25.30    97.20   52    1
1  144     0.01  4.41      28.61     55    28.87     2.06   63    1
2  118     0.08  3.48      32.28     52    29.14     3.81   46    0
3  170     7.50  6.41      38.03     51    31.99    24.26   58    1
4  134    13.60  3.50      27.78     60    25.99    57.34   49    1

In [16]:
df.to_csv('SAHeart_cleaned.csv', index=False)

### 4. Modelling

### 4.1 Linear Regression
-----

In [17]:
# Import Library
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [18]:
# Menyimpan df yang sudah dibersihkan ke variabel cleaned_df
cleaned_df = pd.read_csv('SAHeart_cleaned.csv')

In [19]:
# Import fungsi preprocessing
from sklearn import preprocessing

scaler = preprocessing.RobustScaler()
cleaned_df[['obesity','alcohol']] = scaler.fit_transform(cleaned_df[['obesity','alcohol']])
cleaned_df.head()

   sbp  tobacco   ldl  adiposity  famhist  typea   obesity   alcohol  age  chd
0  160    12.00  5.73      23.11  Present     49 -0.091610  3.835775   52    1
1  144     0.01  4.41      28.61   Absent     55  0.556009 -0.233080   63    1
2  118     0.08  3.48      32.28  Present     52  0.604989 -0.158238   46    0
3  170     7.50  6.41      38.03  Present     51  1.121995  0.716348   58    1
4  134    13.60  3.50      27.78  Present     60  0.033560  2.131081   49    1

In [20]:
# Membuat variabel independen (X) dan variabel dependen (y)
X = cleaned_df[['obesity','alcohol']]
y = cleaned_df['chd']

# Pada tahap selanjutnya, data dibagi menjadi 2 bagian:
# Data Latih (Training Data):  70%
# Data Uji (Testing Data): 30%

In [21]:
# Membagi dataset ke data latih dan data uji

# Import fungsi train_test_split untuk membagi data dari libray sklearn dan modul model_selection
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=0)

In [22]:
# Memanggil fungsi LinearRegression
from sklearn.linear_model import LinearRegression

In [23]:
# Memanggil objek LinearRegression ke dalam variabel mlr
lr = LinearRegression()

# Melatih model
lr.fit(X_train, y_train)

LinearRegression()

In [24]:
# Memprediksi model
y_pred_lr = lr.predict(X_test)
# Nilai prediksi
print("Prediction for test set: {}".format(y_pred_lr))

Prediction for test set: [0.32248764 0.35589616 0.33253691 0.32128458 0.33256199 0.2774368
 0.35160836 0.24587995 0.28135273 0.36237746 0.35417992 0.29504273
 0.38680743 0.35699196 0.41412094 0.33699372 0.34537128 0.27954964
 0.34093938 0.40280544 0.37349251 0.43545827 0.28604836 0.4689096
 0.37356326 0.29266314 0.39068489 0.35664096 0.34965515 0.40772662
 0.37655579 0.3232397  0.32234222 0.36611445 0.30542849 0.25413498
 0.34770034 0.32246302 0.31700576 0.28012988 0.51727217 0.43929234
 0.34882641 0.38362394 0.35518149 0.38256203 0.35680612 0.42972117
 0.40148622 0.36663179 0.2913866  0.34985479 0.19982421 0.34438421
 0.4132101  0.29213866 0.33746089 0.3004384  0.34117148 0.32817403
 0.31946401 0.37025408 0.30866727 0.31012311 0.30631806 0.27308194
 0.36763057 0.32584645 0.3696034  0.46860954 0.3699972  0.37230979
 0.40061645 0.34159542 0.29091604 0.3130877  0.29247152 0.33188009
 0.37837155 0.34244052 0.40618732 0.30888486 0.29045821 0.34714209
 0.33583324 0.26457936 0.37475216 0.32714415 0.35705177 0.42763247
 0.35009634 0.3841697  0.25714475 0.38172792 0.33966284 0.30112833
 0.4892501  0.31703335 0.26888963 0.38352924 0.36192819 0.36251783
 0.47950148 0.29602219 0.31776882 0.45810696 0.38231797 0.32689671
 0.33107524 0.38364529 0.346849   0.31996495 0.37378608 0.39900806
 0.32569146 0.37908045 0.32063086 0.30345376 0.39807206 0.27641632
 0.31517658 0.37586343 0.45733558 0.28400889 0.31146302 0.39057633
 0.30290562 0.29474    0.29248187 0.37185915 0.28720136 0.32549504
 0.37805307 0.56557944 0.3744945  0.3522807  0.26457936 0.24739684
 0.28326319]

In [25]:
# Membandingkan nilai sebenarnya dengan nilai prediksi menggunakan linear regression
lr_diff = pd.DataFrame({'Actual value': y_test, 'Predicted value': y_pred_lr})
lr_diff.head()

     Actual value  Predicted value
113             1         0.322488
21              0         0.355896
78              1         0.332537
118             1         0.321285
225             0         0.332562

In [26]:
# Menerapkan threshold pada variabel y_pred_lr ke dalam variabel y_predict_class
y_predict_class = [1 if prob > 0.5 else 0 for prob in y_pred_lr]

#### Hasil Akurasi Linear Regression

In [27]:
# Import Library
from sklearn.metrics import accuracy_score

# Menghitung Akurasi
print(f"Accuracy from Linear Regression: {round(accuracy_score(y_test, y_predict_class) * 100, 2)}%")
# Membulatkan nilai akurasi menjadi dua angka di belakang koma

Accuracy from Linear Regression: 66.91%

### 5. Evaluation

Hasil prediksi dari Linear Regression sebesar 66.9%